[package]
name = "file-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
toml = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
rust-s3 = "0.33"
